name: Olá, Multiverso!!!

on: [push]

jobs:
  ola_multiverso_jobs:
    runs-on: ubuntu-latest

    steps:
      -name: Checkout
       uses: actions/checkout@v2

      - name: Chamando
       run: echo "Olá, Multiverso da Loucura"